### PR TITLE
Manage Custom Settings in permission sets generation

### PR DESCRIPTION
**Pull request by CatSue**
## Fixes

  - 
  -

## Proposed Changes

  - Add CustomSettings metadataType and update README 
  -

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
thanks for your contribution :)

**Comment by nvuillam** [comment]
@CatSue please can you update the changelog ? thanks :)

**Comment by CatSue** [comment]
@nvuillam Changelog updated :)

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
@CatSue published in v2.4.4 :)

**Pull request merged**
